// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import Footer from "@/Components/Footer";
// import Navbar from "@/Components/Navbar";
// import "./globals.css";
// import ScrollUpButton from "@/Components/ScrollupButton";

// export default function Layout({ children }) {
//   return (
   
//       <html>
//       <body>
//       <div className="bg-white text-gray-900">
//       <Navbar />
//       <main className=" mx-auto p-4">{children}</main>
//       <Footer />
//       <ScrollUpButton/>
//       </div>
//       </body>
//       </html>
    
//   );
// }
import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";
import "./globals.css";
import ScrollUpButton from "@/Components/ScrollupButton";

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className="bg-white text-gray-900">
        <Navbar />
        <main className="mx-auto p-4">{children}</main>
        <Footer />
        <ScrollUpButton />
      </body>
    </html>
  );
}
